import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    screens: {
      xs: "var(--screen-xs)",
      sm: "var(--screen-sm)",
      md: "var(--screen-md)",
      lg: "var(--screen-lg)",
      xl: "var(--screen-xl)",
    },
    extend: {
      maxWidth: {
        xs: "var(--max-width-xs)",
        sm: "var(--max-width-sm)",
        md: "var(--max-width-md)",
        lg: "var(--max-width-lg)",
        xl: "var(--max-width-xl)",
      },
      colors: {
        primary: {
          "50": "var(--primary-50)",
          "100": "var(--primary-100)",
          "200": "var(--primary-200)",
          "300": "var(--primary-300)",
          "400": "var(--primary-400)",
          "500": "var(--primary-500)",
          "600": "var(--primary-600)",
          "700": "var(--primary-700)",
          "800": "var(--primary-800)",
          "900": "var(--primary-900)",
          "950": "var(--primary-950)",
        },
        secondary: {
          "50": "var(--secondary-50)",
          "100": "var(--secondary-100)",
          "200": "var(--secondary-200)",
          "300": "var(--secondary-300)",
          "400": "var(--secondary-400)",
          "500": "var(--secondary-500)",
          "600": "var(--secondary-600)",
          "700": "var(--secondary-700)",
          "800": "var(--secondary-800)",
          "900": "var(--secondary-900)",
          "950": "var(--secondary-950)",
        },
        tertiary: {
          "50": "var(--tertiary-50)",
          "100": "var(--tertiary-100)",
          "200": "var(--tertiary-200)",
          "300": "var(--tertiary-300)",
          "400": "var(--tertiary-400)",
          "500": "var(--tertiary-500)",
          "600": "var(--tertiary-600)",
          "700": "var(--tertiary-700)",
          "800": "var(--tertiary-800)",
          "900": "var(--tertiary-900)",
          "950": "var(--tertiary-950)",
        },
        gray: {
          "50": "var(--gray-50)",
          "100": "var(--gray-100)",
          "200": "var(--gray-200)",
          "300": "var(--gray-300)",
          "400": "var(--gray-400)",
          "500": "var(--gray-500)",
          "600": "var(--gray-600)",
          "700": "var(--gray-700)",
          "800": "var(--gray-800)",
          "900": "var(--gray-900)",
          "950": "var(--gray-950)",
        },
        success: {
          light: "var(--success-light)",
          main: "var(--success-light)",
          dark: "var(--success-light)",
          "contrast-text": "var(--success-light)",
        },
        error: {
          light: "var(--error-light)",
          main: "var(--error-light)",
          dark: "var(--error-light)",
          "contrast-text": "var(--error-light)",
        },
        warning: {
          light: "var(--warning-light)",
          main: "var(--warning-light)",
          dark: "var(--warning-light)",
          "contrast-text": "var(--warning-light)",
        },
        info: {
          light: "var(--info-light)",
          main: "var(--info-light)",
          dark: "var(--info-light)",
          "contrast-text": "var(--info-light)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          disabled: "var(--text-disabled)",
          light: "var(--text-light)",
          dark: "var(--text-dark)",
        },
        // background: "hsl(var(--background))",
        // foreground: "hsl(var(--foreground))",
        // card: {
        //   DEFAULT: "hsl(var(--card))",
        //   foreground: "hsl(var(--card-foreground))",
        // },
        // popover: {
        //   DEFAULT: "hsl(var(--popover))",
        //   foreground: "hsl(var(--popover-foreground))",
        // },
        // primary: {
        //   DEFAULT: "hsl(var(--primary))",
        //   foreground: "hsl(var(--primary-foreground))",
        // },
        // secondary: {
        //   DEFAULT: "hsl(var(--secondary))",
        //   foreground: "hsl(var(--secondary-foreground))",
        // },
        // muted: {
        //   DEFAULT: "hsl(var(--muted))",
        //   foreground: "hsl(var(--muted-foreground))",
        // },
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        // destructive: {
        //   DEFAULT: "hsl(var(--destructive))",
        //   foreground: "hsl(var(--destructive-foreground))",
        // },
        // border: "hsl(var(--border))",
        // input: "hsl(var(--input))",
        // ring: "hsl(var(--ring))",
        // chart: {
        //   "1": "hsl(var(--chart-1))",
        //   "2": "hsl(var(--chart-2))",
        //   "3": "hsl(var(--chart-3))",
        //   "4": "hsl(var(--chart-4))",
        //   "5": "hsl(var(--chart-5))",
        // },
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        lg: "var(--radius-lg)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
