export const MEDIAS = {
    heroImage: "/assets/images/heroImage1.jpg",
    heroVideo: "/assets/videos/Tv Video.mp4",
    aboutUsImage: "/assets/images/aboutUsImage1.jpg",
    aboutUsImage2: "/assets/images/aboutUsImage2.jpg",
    aboutUsImage3: "/assets/images/aboutUsImage3.jpg",
    contentImage11: "/assets/images/contentImage11.jpg",
    contentImage1: "/assets/images/contentImage1.jpg",
    contentImage2: "/assets/images/contentImage2.jpg",
    contentImage3: "/assets/images/contentImage3.jpg",
    contentImage4: "/assets/images/contentImage44.jpg",
    menuKababBanner: "/assets/images/menu/menu-starter.jpg",
    menuStarterBanner: "/assets/images/menu/menu-starter.jpg",
    menuSpecialsBanner: "/assets/images/menu/menu-starter.jpg",
};
