// types
import type { Metadata } from "next";
// stylesheets
import "./globals.css";
import "@/theme/palette.css";
import "@/theme/shape.css";
import "@/theme/breakpoints.css";
// libs
import { Geist, Geist_Mono } from "next/font/google";
import { getLocale, getMessages } from "next-intl/server";
// providers
import { I18nProvider } from "@/providers/I18nProvider";
import { ReduxProvider } from "@/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={"rtl"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <I18nProvider messages={messages}>{children}</I18nProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
