// libs
import { Roboto } from "next/font/google";
import { getLanguageDirection } from "@/i18n/request";
import { getLocale, getMessages } from "next-intl/server";
// providers
import { I18nProvider } from "@/providers/I18nProvider";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
// types
import type { Metadata } from "next";
// stylesheets
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import "./globals.css";
import "@/theme/palette.css";
import "@/theme/shape.css";
import "@/theme/breakpoints.css";

const RobotoFont = Roboto({
    variable: "--font-roboto",
    weight: ["100", "300", "400", "500", "700", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();
    const dir = getLanguageDirection(locale);
    return (
        <html lang={locale} dir={dir} suppressHydrationWarning>
            <body className={`${RobotoFont.className} antialiased`}>
                <ReduxProvider>
                    <ThemeProvider>
                        <I18nProvider messages={messages}>
                            {children}
                        </I18nProvider>
                    </ThemeProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
